# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: monorepo
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: monorepo
#   template:
#     metadata:
#       labels:
#         app: monorepo
#     spec:
#       containers:
#         - name: monorepo
#           image: 340752829568.dkr.ecr.us-east-1.amazonaws.com/monorepo:latest
#           ports:
#             - containerPort: 3000


apiVersion: apps/v1
kind: Deployment
metadata:
  name: monorepo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monorepo
  template:
    metadata:
      labels:
        app: monorepo
    spec:
      containers:
      - name: monorepo
        image: 340752829568.dkr.ecr.us-east-1.amazonaws.com/monorepo:latest
        ports:
        - containerPort: 3000