name: Deploy to EKS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: thisEkS
  ECR_REPOSITORY: monorepo
  ECR_REGISTRY: 340752829568.dkr.ecr.us-east-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      # Now using the separate k8s files
      - name: Deploy to Kubernetes
        run: |
          # Apply both files
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          # Check deployment status
          kubectl rollout status deployment/monorepo
